services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: gtdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ../gt-front
    ports:
      - "8080:8080"
    depends_on:
      - db

  e2e:
    build: ../e2e
    depends_on:
      - db
      - gt-front

volumes:
  db-data: